#!/usr/bin/env node
/**
 * Planning Agent - Interactive AI-driven planning tool
 * 
 * This module implements a planning agent that:
 * 1. Maintains an expandable plan graph (DOT format)
 * 2. Interacts with Grill skill through subprocess calls
 * 3. Proactively identifies areas needing more detail
 * 4. Generates output in plan.md and plan.dot formats
 * 5. Breaks down plans into tracer-bullet tickets with dependencies
 */

const { spawnSync } = require('child_process');
const path = require('path');
const fs = require('fs');
const os = require('os');

class PlanningAgent {
  constructor() {
    this.planGraph = null; // Will be DOT-format string + internal representation
    this.nodes = new Map(); // ID -> node object
    this.round = 0;
    this.maxRounds = Infinity;
    this.outputDir = process.cwd();
    this.interactive = true;
  }

  /**
   * Initialize the planning session with high-level context
   */
  init(context) {
    this.round = 0;
    
    // Create root node
    const rootId = 'AREA-001';
    this.nodes.set(rootId, {
      id: rootId,
      type: 'area',
      description: context.project || 'Planning Project',
      children: [],
      status: 'unexpanded',
      question: null,
      parent: null
    });

    this.planGraph = this._buildGraphStructure();
    console.log(`Plan initialized: ${this.nodes.get(rootId).description}`);
    return this;
  }

  /**
   * Build internal tree structure from nodes map
   */
  _buildGraphStructure() {
    const buildNode = (nodeId) => {
      const node = this.nodes.get(nodeId);
      if (!node) return null;
      
      const result = {
        id: node.id,
        type: node.type,
        description: node.description,
        children: node.children.map(childId => buildNode(childId)),
        status: node.status,
        dependencies: node.dependencies || []
      };
      
      return result;
    };

    // Find root nodes (no parent or parent not found)
    const roots = Array.from(this.nodes.values())
      .filter(n => !n.parent || !this.nodes.has(n.parent));
    
    return {
      version: '1.0',
      timestamp: new Date().toISOString(),
      nodes: Object.fromEntries(this.nodes.entries()),
      trees: roots.map(buildNode)
    };
  }

  /**
   * Generate DOT format representation of the plan graph
   */
  generateDOT() {
    let dot = 'digram PlanGraph {\n';
    dot += '  rankdir=TB;\n';
    dot += '  node [shape=box, style=filled];\n\n';

    // Color codes for different types and statuses
    const typeColors = {
      area: '#AED6F1',      // Blue
      task: '#58D68D',      // Green  
      decision: '#F9E79F',  // Yellow
      milestone: '#E8DAEF'  // Purple
    };

    const statusStyles = {
      unexpanded: { fillcolor: '#FFCCCC', color: '#CC0000' },
      partial: { fillcolor: '#FFFFCC', color: '#CC9900' },
      complete: { fillcolor: '#CCFFCC', color: '#006600' }
    };

    // Add nodes
    for (const [id, node] of this.nodes) {
      const typeColor = typeColors[node.type] || '#FFFFFF';
      const status = statusStyles[node.status] || { fillcolor: '#FFFFFF', color: '#000000' };
      
      dot += `  ${id} [label="${node.id}\\n${node.type}: ${node.description.substring(0, 40)}", `;
      dot += `fillcolor:${status.fillcolor}, color:${status.color}, fontcolor:${status.color}, `;
      dot += `shape=ellipse];\n`;
    }

    // Add edges (parent-child relationships)
    for (const [id, node] of this.nodes) {
      if (node.parent && this.nodes.has(node.parent)) {
        dot += `  ${node.parent} -> ${id};\n`;
      }
      if (node.children && node.children.length > 0) {
        for (const childId of node.children) {
          dot += `  ${id} -> ${childId};\n`;
        }
      }
    }

    dot += '}';
    return dot;
  }

  /**
   * Generate Markdown output (plan.md) with ticket breakdown
   */
  generateMarkdown(includeTickets = true) {
    const title = this.nodes.get('AREA-001')?.description || 'Planning Document';
    
    let md = `# ${title}\n\n`;
    md generated by Planning Agent\n`;
    md * Last updated: ${new Date().toLocaleString()}\n\n`;

    // Add graph summary
    md '## Plan Structure\n\n';
    this._addTreeMarkdown(md, 'AREA-001', 0);
    md += '\n';

    // Add ticket breakdown if requested
    if (includeTickets) {
      md += '## Actionable Tickets\n\n';
      const tickets = this.breakdownIntoTickets();
      
      tickets.forEach((ticket, idx) => {
        md += `### Ticket ${idx + 1}: ${ticket.title}\n\n`;
        md += '**What to build:** ${ticket.what}\n\n`;
        md += '**Blocked by:** ${ticket.blockedBy || 'None — can start immediately'}\n\n`;
        md += '**Acceptance criteria:**\n`;
        ticket.criteria.forEach(criterion => md += `- [ ] ${criterion}\n`);
        md += '\n';
      });
    }

    return md;
  }

  /**
   * Helper to recursively add tree structure to markdown
   */
  _addTreeMarkdown(md, nodeId, depth) {
    const node = this.nodes.get(nodeId);
    if (!node) return md;

    const indent = '  '.repeat(depth);
    const statusIcon = node.status === 'complete' ? '✅ ' : 
                       node.status === 'partial' ? '⚠️ ' : '❌ ';
    
    md += `${indent}* ${statusIcon}${node.id} (${node.type}): ${node.description}\n`;
    
    if (node.children && node.children.length > 0) {
      for (const childId of node.children) {
        this._addTreeMarkdown(md, childId, depth + 1);
      }
    }

    return md;
  }

  /**
   * Break down the plan graph into tracer-bullet tickets
   */
  breakdownIntoTickets() {
    const tickets = [];
    let ticketCounter = 1;
    const ticketMap = new Map(); // nodeId -> ticketIndex

    // Find leaf tasks and work backwards to create vertical slices
    const findLeafTasks = (nodeId) => {
      const node = this.nodes.get(nodeId);
      if (!node || node.children.length === 0) {
        return [nodeId];
      }
      const leaves = [];
      for (const childId of node.children) {
        leaves.push(...findLeafTasks(childId));
      }
      return leaves;
    };

    // Group related tasks into tickets based on shared ancestry and dependencies
    const groupTasksIntoTickets = () => {
      // Simplified grouping logic - in practice would be more sophisticated
      const visited = new Set();
      
      const traverse = (nodeId) => {
        if (visited.has(nodeId)) return;
        visited.add(nodeId);
        
        const node = this.nodes.get(nodeId);
        if (node.type === 'task' && node.status !== 'unexpanded') {
          // Find the largest common ancestor for this task
          let current = nodeId;
          while (node.parent) {
            if (this.nodes.get(node.parent).type === 'area') {
              break;
            }
            current = node.parent;
            node = this.nodes.get(current);
          }
          
          // Check if there's already a ticket for this area
          let ticketIdx = Array.from(ticketMap.values()).findIndex(
            t => t.ancestor === current
          );
          
          if (ticketIdx === -1) {
            ticketIdx = tickets.length;
            tickets.push({
              id: `T-${ticketCounter++}`,
              title: `${node.description} - Implementation`,
              what: `Deliver end-to-end capability for ${node.description}`,
              blockedBy: node.dependencies || [],
              ancestor: current,
              criteria: []
            });
          }
          
          if (tickets[ticketIdx].criteria.length < 3) {
            tickets[ticketIdx].criteria.push(`Complete ${node.description} sub-task`);
          }
        }
        
        if (node.children) {
          for (const childId of node.children) {
            traverse(childId);
          }
        }
      };

      // Start from all root areas
      for (const [id, node] of this.nodes) {
        if (node.type === 'area' && !node.parent) {
          traverse(id);
        }
      }

      // Ensure each ticket has at least one criterion
      for (const ticket of tickets) {
        if (ticket.criteria.length === 0) {
          ticket.criteria.push('Verify functionality works end-to-end');
        }
      }

      return tickets;
    };

    return groupTasksIntoTickets();
  }

  /**
   * Query the Grill skill for more information
   */
  async queryGrillSkill(frontierNodes = []) {
    // Prepare input data
    const input = {
      planGraph: this._buildGraphStructure(),
      currentRound: this.round,
      frontierNodes: frontierNodes,
      requiredContext: ['project scope', 'timeline constraints', 'resources available']
    };

    // Write input to temporary file
    const inputFile = path.join(os.tmpdir(), `grill-input-${Date.now()}.json`);
    fs.writeFileSync(inputFile, JSON.stringify(input, null, 2));

    // Call grill skill as subprocess
    let grillResult;
    try {
      // This assumes there's a grill skill executable or script
      grillResult = spawnSync('python', [
        path.join(__dirname, '..', 'scripts', 'grill-skill.py'),
        inputFile
      ], { encoding: 'utf-8' });

      if (grillResult.status !== 0) {
        // Fallback: use simpler grill interaction
        console.log('Grill skill not found, using mock response');
        return this._mockGrillResponse(frontierNodes);
      }
    } catch (e) {
      console.log('Using mock grill response due to error:', e.message);
      return this._mockGrillResponse(frontierNodes);
    }

    // Parse output
    const outputPath = outputFile.replace('.input.json', '.output.json');
    if (fs.existsSync(outputPath)) {
      const output = fs.readFileSync(outputPath, 'utf-8');
      return JSON.parse(output);
    }

    return this._mockGrillResponse(frontierNodes);
  }

  /**
   * Mock grill response for demonstration when real skill isn't available
   */
  _mockGrillResponse(frontierNodes) {
    // Simulate getting answers and discovering new areas to explore
    const newNodes = [];
    const questionsToAsk = [];
    const answers = {};

    frontierNodes.forEach(nodeId => {
      const node = this.nodes.get(nodeId);
      if (node && node.type === 'decision') {
        answers[nodeId] = `Answer for ${node.description} (simulated)`;
        // Add a task node below this decision
        const newTaskId = `TASK-${String(this.nodes.size + 1).padStart(3, '0')}`;
        this.nodes.set(newTaskId, {
          id: newTaskId,
          type: 'task',
          description: `Implement ${node.description}`,
          status: 'partial',
          children: [],
          parent: nodeId
        });
        node.children.push(newTaskId);
        newNodes.push(newTaskId);
      }
    });

    // Proactively find more areas to ask about
    this._findExpandableAreas(questionsToAsk);

    return {
      answers,
      newNodes: newNodes.map(id => ({
        id,
        type: 'task',
        description: `Implementation for related area`,
        status: 'partial'
      })),
      questions_to_ask: questionsToAsk
    };
  }

  /**
   * Find areas in the plan that could benefit from additional questioning
   */
  _findExpandableAreas(questionsList) {
    // Look for areas that are still unexpanded but have descendants
    const expandable = [];
    
    const search = (nodeId) => {
      const node = this.nodes.get(nodeId);
      if (!node) return;
      
      if (node.type === 'area' && node.status === 'unexpanded') {
        expandable.push(nodeId);
      }
      
      if (node.children) {
        for (const childId of node.children) {
          search(childId);
        }
      }
    };

    // Start from root nodes
    for (const [id, node] of this.nodes) {
      if (!node.parent || node.type === 'area') {
        search(id);
      }
    }

    // Limit to top 3 expandable areas
    questionsList.push(...expandable.slice(0, 3));
  }

  /**
   * Process responses from Grill skill and update plan graph
   */
  processGrillResponse(response) {
    this.round++;

    // Update node statuses based on answers
    if (response.answers) {
      for (const [nodeId, answer] of Object.entries(response.answers)) {
        const node = this.nodes.get(nodeId);
        if (node) {
          node.status = node.status === 'unexpanded' ? 'partial' : 'complete';
          // Could store answer somewhere on the node if needed
        }
      }
    }

    // Add new nodes from response
    if (response.new_nodes) {
      response.new_nodes.forEach(newNode => {
        this.nodes.set(newNode.id, {
          id: newNode.id,
          type: newNode.type || 'task',
          description: newNode.description || `Node ${newNode.id}`,
          status: newNode.status || 'partial',
          children: [],
          parent: newNode.parent || this._findParentForNewNode(),
          question: null
        });

        // Add to parent's children list
        const parent = this.nodes.get(newNode.parent);
        if (parent && parent.children) {
          parent.children.push(newNode.id);
        }
      });
    }

    // Mark processed frontier nodes
    if (response.questions_to_ask) {
      response.questions_to_ask.forEach(nodeId => {
        const node = this.nodes.get(nodeId);
        if (node) node.status = 'complete';
      });
    }

    // Rebuild graph structure
    this.planGraph = this._buildGraphStructure();

    console.log(`Round ${this.round}: Updated plan graph, added ${response?.new_nodes?.length || 0} new nodes`);
  }

  /**
   * Find a suitable parent for newly introduced nodes
   */
  _findParentForNewNode() {
    // Find most recently completed area or decision as parent
    const candidates = Array.from(this.nodes.values())
      .filter(n => (n.status === 'complete' || n.status === 'partial') && 
                   (n.type === 'area' || n.type === 'decision'))
      .sort((a, b) => b.id.localeCompare(a.id)) // Sort by ID descending for recent
      .slice(0, 3);

    return candidates.length > 0 ? candidates[0].id : 'AREA-001';
  }

  /**
   * Get frontier nodes (nodes that need more information or expansion)
   */
  getFrontierNodes() {
    const frontier = [];

    const findFrontier = (nodeId) => {
      const node = this.nodes.get(nodeId);
      if (!node) return;

      // If it's a decision point without answer, it's in the frontier
      if (node.type === 'decision' && node.status === 'unexpanded') {
        frontier.push(nodeId);
        return;
      }

      // If it has children that aren't resolved yet, check them
      if (node.children && node.children.length > 0) {
        for (const childId of node.children) {
          findFrontier(childId);
        }
      } else if (node.type !== 'milestone' && node.status === 'unexpanded') {
        // Leaf area/task that hasn't been expanded
        frontier.push(nodeId);
      }
    };

    // Start from root nodes
    for (const [id, node] of this.nodes) {
      if (!node.parent || node.type === 'area') {
        findFrontier(id);
      }
    }

    return frontier;
  }

  /**
   * Check if there are more nodes to expand
   */
  hasMoreFrontier() {
    return this.getFrontierNodes().length > 0;
  }

  /**
   * Main run method for interactive planning session
   */
  async runInteractive(maxRounds = 10) {
    this.maxRounds = maxRounds;
    console.log('\n=== Planning Session Started ===\n');

    // Initial run
    await this.expandPlan();

    while (this.round < this.maxRounds && this.hasMoreFrontier()) {
      const shouldContinue = await this._askUserContinue();
      if (!shouldContinue) break;

      await this.expandPlan();
    }

    // Final outputs
    this._generateFinalOutputs();

    console.log('\n=== Planning Session Complete ===\n');
    return this;
  }

  /**
   * Single round of plan expansion
   */
  async expandPlan() {
    const frontier = this.getFrontierNodes();
    
    if (frontier.length === 0) {
      console.log('No more frontier nodes to expand.');
      return;
    }

    console.log(`\n--- Round ${this.round + 1} ---`);
    console.log(`Frontier nodes to explore: ${frontier.length}`);

    // Query grill skill
    const response = await this.queryGrillSkill(frontier);
    
    // Process results
    this.processGrillResponse(response);

    // Also proactively look for additional expansion opportunities
    this._findExpandableAreas(expandableQuestions);
    if (expandableQuestions.length > 0) {
      console.log(`Proactively identified ${expandableQuestions.length} additional areas for exploration`);
    }
  }

  /**
   * Ask user whether to continue
   */
  async _askUserContinue() {
    // In a real interactive mode, this would prompt the user
    // For now, auto-continue for demonstration
    return true; 
  }

  /**
   * Generate final output files
   */
  _generateFinalOutputs() {
    // Generate plan.md
    const markdown = this.generateMarkdown(true);
    const mdPath = path.join(this.outputDir, 'plan.md');
    fs.writeFileSync(mdPath, markdown);
    console.log(`Generated: ${mdPath}`);

    // Generate plan.dot
    const dotContent = this.generateDOT();
    const dotPath = path.join(this.outputDir, 'plan.dot');
    fs.writeFileSync(dotPath, dotContent);
    console.log(`Generated: ${dotPath}`);

    // Also save internal state for resuming
    const statePath = path.join(this.outputDir, 'planning-state.json');
    fs.writeFileSync(statePath, JSON.stringify(this.planGraph, null, 2));
    console.log(`State saved: ${statePath}`);
  }
}

// CLI Entry Point
if (require.main === module) {
  const args = process.argv.slice(2);
  const action = args[0] || 'help';

  const planningAgent = new PlanningAgent();

  switch (action) {
    case 'init':
      const projectName = args[1] || 'Untitled Project';
      planningAgent.init({ project: projectName });
      planningAgent._generateFinalOutputs();
      break;

    case 'expand':
      // Simulate loading existing state
      planningAgent.init({ project: 'Sample Project' });
      planningAgent.runInteractive(3);
      break;

    case 'help':
    case '-h':
    case '--help':
      console.log(`
Usage: planning-agent <command> [options]

Commands:
  init <project-name>     Initialize planning session with project name
  expand                  Perform expansion of the plan
  help, -h, --help        Show this help message

Examples:
  planning-init "AI Agent Development"
  planning-agent expand
      `);
      break;

    default:
      console.log(`Unknown command: ${action}`);
      console.log('Run planning-agent --help for usage');
      process.exit(1);
  }
}

module.exports = { PlanningAgent };
